In [3]:
import pandas as pd
import torch

torch.cuda.get_device_name(0)

'NVIDIA GeForce RTX 4080'

In [2]:
df = pd.read_excel('Mergerd_c1.xlsx')

print(df.groupby(['plot', 'prow', 'pcol'])['entry'].nunique().all())

True

In [4]:
# number of unique value of plot
print(df['plot'].nunique())

1981

In [5]:
print(df['entry'].nunique())

634

In [9]:
# for plot = 1322, print all rows
df.loc[df['plot'] == 1322]

,date_x,time_x,stage_x,wind_x,cloud_x,temp_x,expt,loc,plot,prow,...,linolenic,lysine,methionine,oleic,palmitic,raffinose,stachyose,sucrose,threonine,tryptophan
13,23234,1308,R5,2.6,17,37.2,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
14,23234,1308,R5,2.6,17,37.2,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
15,23234,1308,R5,2.6,17,37.2,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
16,23234,1308,R5,2.6,17,37.2,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
17,23234,1308,R5,2.6,17,37.2,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
18,23234,1308,R5,2.6,17,37.2,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
19,23234,1308,R5,2.6,17,37.2,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
20,23234,1308,R5,2.6,17,37.2,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
21,23234,1308,R5,2.6,17,37.2,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
22,23234,1308,R5,2.6,17,37.2,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
23,23234,1308,R5,2.6,17,37.2,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
24,23234,1308,R5,2.6,17,37.2,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
25,23234,1308,R5,2.6,17,37.2,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
8593,23241,1240,R5,6.1,1,32.2,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
8594,23241,1240,R5,6.1,1,32.2,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
8595,23241,1240,R5,6.1,1,32.2,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
8596,23241,1240,R5,6.1,1,32.2,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
8597,23241,1240,R5,6.1,1,32.2,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
8598,23241,1240,R5,6.1,1,32.2,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
8599,23241,1240,R5,6.1,1,32.2,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
8600,23241,1240,R5,6.1,1,32.2,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
8601,23241,1240,R5,6.1,1,32.2,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
8602,23241,1240,R5,6.1,1,32.2,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
8603,23241,1240,R5,6.1,1,32.2,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
8604,23241,1240,R5,6.1,1,32.2,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
8605,23241,1240,R5,6.1,1,32.2,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
17173,23250,1411,R7,7.0,7,31.1,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
17174,23250,1411,R7,7.0,7,31.1,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
17175,23250,1411,R7,7.0,7,31.1,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
17176,23250,1411,R7,7.0,7,31.1,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
17177,23250,1411,R7,7.0,7,31.1,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
17178,23250,1411,R7,7.0,7,31.1,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
17179,23250,1411,R7,7.0,7,31.1,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
17180,23250,1411,R7,7.0,7,31.1,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
17181,23250,1411,R7,7.0,7,31.1,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
17182,23250,1411,R7,7.0,7,31.1,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
17183,23250,1411,R7,7.0,7,31.1,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
17184,23250,1411,R7,7.0,7,31.1,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
17185,23250,1411,R7,7.0,7,31.1,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
25753,23256,1150,R7,1.7,11,26.7,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
25754,23256,1150,R7,1.7,11,26.7,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
25755,23256,1150,R7,1.7,11,26.7,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
25756,23256,1150,R7,1.7,11,26.7,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
25757,23256,1150,R7,1.7,11,26.7,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
25758,23256,1150,R7,1.7,11,26.7,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
25759,23256,1150,R7,1.7,11,26.7,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
25760,23256,1150,R7,1.7,11,26.7,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
25761,23256,1150,R7,1.7,11,26.7,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
25762,23256,1150,R7,1.7,11,26.7,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
25763,23256,1150,R7,1.7,11,26.7,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
25764,23256,1150,R7,1.7,11,26.7,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
25765,23256,1150,R7,1.7,11,26.7,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.

In [10]:
file_path_1 = '/home/g/ghanaatian/MYFILES/Projects/Agriculture/TO CARAGEA WORKING 2022_2023 ALL LOC_KPEGG_MULTISPECTRAL_stacked.xls'
sheet_name_1 = 'ALL MULTISPECTRAL'

df_1 = pd.read_excel(file_path_1, sheet_name=sheet_name_1)

In [12]:
df_1.loc[df_1['plot'] == 1322]

,date,time,stage,wind,cloud,temp,expt,loc,plot,prow,...,linolenic,lysine,methionine,oleic,palmitic,raffinose,stachyose,sucrose,threonine,tryptophan
1,23173,1356,V4,4.34,36,31.0,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
661,23179,1332,V6.5,2.60,12,35.6,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
1321,23187,1347,R1,4.30,44,25.0,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
1981,23193,1345,R2,8.70,61,33.3,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
2641,23198,1350,R2,7.80,43,30.6,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
3301,23206,1352,R2,8.70,50,37.2,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
3961,23219,1411,R4,5.20,7,26.1,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
4621,23227,1334,R5,5.20,1,25.6,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
5281,23234,1217,R5,2.60,9,37.0,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
5941,23241,1150,R5,6.10,1,31.7,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
6601,23250,1312,R6,7.00,5,30.0,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
7261,23255,1341,R7,4.30,1,25.0,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
7921,23261,1322,R7,10.43,5,32.8,23 KPE GG F1,F1,1322,17,...,.,.,.,.,.,.,.,.,.,.
22181,22221,1015,.,3.00,3,23.3,22 KPE GG F2,F2,1322,2,...,8.92,2.64,0.56,16.55,10.2,0.85,3.39,4.81,1.53,0.37
22841,22230,1149,.,5.20,3,26.7,22 KPE GG F2,F2,1322,2,...,8.92,2.64,0.56,16.55,10.2,0.85,3.39,4.81,1.53,0.37
23501,22234,1412,.,7.00,32,28.3,22 KPE GG F2,F2,1322,2,...,8.92,2.64,0.56,16.55,10.2,0.85,3.39,4.81,1.53,0.37
24161,22250,1242,.,7.80,3,28.9,22 KPE GG F2,F2,1322,2,...,8.92,2.64,0.56,16.55,10.2,0.85,3.39,4.81,1.53,0.37
24821,22255,1318,.,11.30,2,25.6,22 KPE GG F2,F2,1322,2,...,8.92,2.64,0.56,16.55,10.2,0.85,3.39,4.81,1.53,0.37
25481,22262,1050,R6,9.60,17,28.9,22 KPE GG F2,F2,1322,2,...,8.92,2.64,0.56,16.55,10.2,0.85,3.39,4.81,1.53,0.37
26141,22279,1430,R7,6.10,2,26.1,22 KPE GG F2,F2,1322,2,...,8.92,2.64,0.56,16.55,10.2,0.85,3.39,4.81,1.53,0.37
26801,22292,1450,R8,8.70,30,15.0,22 KPE GG F2,F2,1322,2,...,8.92,2.64,0.56,16.55,10.2,0.85,3.39,4.81,1.53,0.37

In [14]:
# print plot and expt for entry = 621
df.loc[df['entry'] == 621][['entry','plot', 'expt']]

      entry  plot          expt
0       621  1321  23 KPE GG F1
1       621  1321  23 KPE GG F1
2       621  1321  23 KPE GG F1
3       621  1321  23 KPE GG F1
4       621  1321  23 KPE GG F1
...     ...   ...           ...
74915   621  1320  23 KPE GG AW
74916   621  1320  23 KPE GG AW
74917   621  1320  23 KPE GG AW
74918   621  1320  23 KPE GG AW
74919   621  1320  23 KPE GG AW

[448 rows x 3 columns]

In [22]:
# print number of uniqe plot and expt for entry = 621
df.loc[df['entry'] == 621][['plot', 'expt']].nunique()

# for entry = 621, print all unique combination of plot and expt
df.loc[df['entry'] == 199][['plot', 'loc', 'expt']].drop_duplicates()

       plot loc           expt
1378   1427  F1   23 KPE GG F1
37310   300  AW  23 KPE GG AWD
43100   859  AW   23 KPE GG AW

In [23]:
# for each unique entry, number of unique plot and expt
df.groupby('entry')[['plot', 'expt']].nunique()

       plot  expt
entry
1         3     3
2         3     3
3         3     3
4         3     3
5         3     3
...     ...   ...
630       9     3
631       9     3
632       9     3
633       9     3
.         1     1

[634 rows x 2 columns]

In [35]:
# number of unique combinations of plot, expt, entry
df_1.groupby(['plot', 'expt', 'entry']).size().reset_index().rename(columns={0: 'count'}).T

,0,1,2,3,4,5,6,7,8,9,...,2631,2632,2633,2634,2635,2636,2637,2638,2639,2640
plot,1,2,3,4,5,6,7,8,9,10,...,1976,1977,1977,1978,1978,1979,1979,1980,1980,.
expt,23 KPE GG AWD,23 KPE GG AWD,23 KPE GG AWD,23 KPE GG AWD,23 KPE GG AWD,23 KPE GG AWD,23 KPE GG AWD,23 KPE GG AWD,23 KPE GG AWD,23 KPE GG AWD,...,23 KPE GG F1,22 KPE GG F2,23 KPE GG F1,22 KPE GG F2,23 KPE GG F1,22 KPE GG F2,23 KPE GG F1,22 KPE GG F2,23 KPE GG F1,FILLER PLOT
entry,621,426,204,235,147,459,442,328,30,42,...,423,251,318,198,618,151,491,621,621,.
count,10,10,10,10,10,10,10,10,10,10,...,13,8,13,8,13,8,13,8,13,400

In [30]:
# sum up number of unique combinations of plot, expt, entry
df_1.groupby(['plot', 'expt', 'entry']).size().sum()

27460

In [31]:
# nuber of unique yield
df_1['yield'].nunique()

2585

In [38]:
#???#

# for plot=1, expt=23 KPE GG AWD, entry=621 print all yield values
print(df_1.loc[(df_1['plot'] == 1) & (df_1['expt'] == 'KPE GG AWD') & (df_1['entry'] == 621)]['yield'])

#???#

Series([], Name: yield, dtype: object)

In [ ]:
# same enrty for different(plot and expt) -> different yield

In [ ]:
# expt, plot, entry(geno) -> plant/yield/mat(pheno)

In [40]:
# print yield,plot, expt  for entry 621
df_1.loc[df_1['entry'] == 621][['yield', 'plot', 'expt']].T

,0,221,442,659,660,881,1102,1319,1320,1541,...,25922,26139,26140,26361,26582,26799,26800,27021,27242,27459
yield,58.739494,58.014429,41.523482,24.041117,58.739494,58.014429,41.523482,24.041117,58.739494,58.014429,...,46.077128,44.943222,40.344068,47.070503,46.077128,44.943222,40.344068,47.070503,46.077128,44.943222
plot,1321,1542,1763,1980,1321,1542,1763,1980,1321,1542,...,1763,1980,1321,1542,1763,1980,1321,1542,1763,1980
expt,23 KPE GG F1,23 KPE GG F1,23 KPE GG F1,23 KPE GG F1,23 KPE GG F1,23 KPE GG F1,23 KPE GG F1,23 KPE GG F1,23 KPE GG F1,23 KPE GG F1,...,22 KPE GG F2,22 KPE GG F2,22 KPE GG F2,22 KPE GG F2,22 KPE GG F2,22 KPE GG F2,22 KPE GG F2,22 KPE GG F2,22 KPE GG F2,22 KPE GG F2

In [42]:
# print yield for entry 621, plot 1321
df_1.loc[(df_1['entry'] == 621) & (df_1['plot'] == 1321)]['yield']

0        58.739494
660      58.739494
1320     58.739494
1980     58.739494
2640     58.739494
3300     58.739494
3960     58.739494
4620     58.739494
5280     58.739494
5940     58.739494
6600     58.739494
7260     58.739494
7920     58.739494
22180    40.344068
22840    40.344068
23500    40.344068
24160    40.344068
24820    40.344068
25480    40.344068
26140    40.344068
26800    40.344068
Name: yield, dtype: object

In [43]:
# print yield, expt, stage for entry 621, plot 1321
df_1.loc[(df_1['entry'] == 621) & (df_1['plot'] == 1321)][['yield', 'expt', 'stage']].T

,0,660,1320,1980,2640,3300,3960,4620,5280,5940,...,7260,7920,22180,22840,23500,24160,24820,25480,26140,26800
yield,58.739494,58.739494,58.739494,58.739494,58.739494,58.739494,58.739494,58.739494,58.739494,58.739494,...,58.739494,58.739494,40.344068,40.344068,40.344068,40.344068,40.344068,40.344068,40.344068,40.344068
expt,23 KPE GG F1,23 KPE GG F1,23 KPE GG F1,23 KPE GG F1,23 KPE GG F1,23 KPE GG F1,23 KPE GG F1,23 KPE GG F1,23 KPE GG F1,23 KPE GG F1,...,23 KPE GG F1,23 KPE GG F1,22 KPE GG F2,22 KPE GG F2,22 KPE GG F2,22 KPE GG F2,22 KPE GG F2,22 KPE GG F2,22 KPE GG F2,22 KPE GG F2
stage,V4,V6.5,R1,R2,R2,R2,R4,R5,R5,R5,...,R7,R7,.,.,.,.,.,R6,R7,R8

In [44]:
# different expt and same entry are yield values different?
df_1.loc[df_1['entry'] == 621].groupby('expt')['yield'].nunique()

expt
22 KPE GG F2     4
23 KPE GG AW     4
23 KPE GG AWD    4
23 KPE GG F1     4
Name: yield, dtype: int64

In [46]:
df_1.loc[df_1['entry'] == 621].groupby(['expt','plot'])['yield'].nunique()

expt           plot
22 KPE GG F2   1321    1
               1542    1
               1763    1
               1980    1
23 KPE GG AW   661     1
               882     1
               1103    1
               1320    1
23 KPE GG AWD  1       1
               222     1
               443     1
               660     1
23 KPE GG F1   1321    1
               1542    1
               1763    1
               1980    1
Name: yield, dtype: int64

In [ ]:
# plot, expt, entry -> yield
# diff stage , same (plot, expt, entry) -> yield (ONLY multi spectral data)

# aggreate stage, predict yield 

# merge thermal and multispectral data -> unique plot, expt, entry

In [50]:
df_1.loc[(df_1['entry'] == 621) & (df_1['plot'] == 1321) & (df_1['loc'] == 'F1')]

,date,time,stage,wind,cloud,temp,expt,loc,plot,prow,...,linolenic,lysine,methionine,oleic,palmitic,raffinose,stachyose,sucrose,threonine,tryptophan
0,23173,1356,V4,4.34,36,31.0,23 KPE GG F1,F1,1321,16,...,.,.,.,.,.,.,.,.,.,.
660,23179,1332,V6.5,2.60,12,35.6,23 KPE GG F1,F1,1321,16,...,.,.,.,.,.,.,.,.,.,.
1320,23187,1347,R1,4.30,44,25.0,23 KPE GG F1,F1,1321,16,...,.,.,.,.,.,.,.,.,.,.
1980,23193,1345,R2,8.70,61,33.3,23 KPE GG F1,F1,1321,16,...,.,.,.,.,.,.,.,.,.,.
2640,23198,1350,R2,7.80,43,30.6,23 KPE GG F1,F1,1321,16,...,.,.,.,.,.,.,.,.,.,.
3300,23206,1352,R2,8.70,50,37.2,23 KPE GG F1,F1,1321,16,...,.,.,.,.,.,.,.,.,.,.
3960,23219,1411,R4,5.20,7,26.1,23 KPE GG F1,F1,1321,16,...,.,.,.,.,.,.,.,.,.,.
4620,23227,1334,R5,5.20,1,25.6,23 KPE GG F1,F1,1321,16,...,.,.,.,.,.,.,.,.,.,.
5280,23234,1217,R5,2.60,9,37.0,23 KPE GG F1,F1,1321,16,...,.,.,.,.,.,.,.,.,.,.
5940,23241,1150,R5,6.10,1,31.7,23 KPE GG F1,F1,1321,16,...,.,.,.,.,.,.,.,.,.,.
6600,23250,1312,R6,7.00,5,30.0,23 KPE GG F1,F1,1321,16,...,.,.,.,.,.,.,.,.,.,.
7260,23255,1341,R7,4.30,1,25.0,23 KPE GG F1,F1,1321,16,...,.,.,.,.,.,.,.,.,.,.
7920,23261,1322,R7,10.43,5,32.8,23 KPE GG F1,F1,1321,16,...,.,.,.,.,.,.,.,.,.,.

In [ ]:
'''
for one expt, plot, entry combination, aggregate all the spectral/thermal data and predict yield/maturity 

For one expt, plot, entry, stage (thermal and spectral data available) combination, use directly the data at that stage to predict yield 
	- what stage is most predictive (in other words, gives the smallest RMSE error)?
	

For spectral, we can consider all stages for which we have data and we can see if spectral data by itself at a particular stage can predict yield
'''